### ISSUE TITLE
BGLiMS command issues when running JAMMR examples

### ISSUE THREAD

**Issue by igbucur** [pjnewcombe/R2BGLiMS#12]
Hello,

I am having trouble running the latest version of JAM-MR. I tried running the first given examples for the JAMMR function, but I get the following error:

```
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:939)
	at java.base/java.util.Scanner.next(Scanner.java:1594)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
	at Objects.Data.<init>(Data.java:360)
	at bglims.BGLiMS.main(BGLiMS.java:81)
```

After doing a little debugging, it seems to me like something might be amiss when the BGLiMS command is pasted together. The actual part that fails is "system(comm)" in R2BGLiMS.R. The command itself is:

```
java -jar \"/home/gbucur/R/x86_64-pc-linux-gnu-library/3.6/R2BGLiMS/BGLiMS/BGLiMS.jar\" \"/tmp/RtmpVQRGoe/file436947f03241_feb05143307_Arguments.txt\" \"/tmp/RtmpVQRGoe/file43692f02b2db_feb05143307_Data.txt\" \"/tmp/RtmpVQRGoe/file436961c13ce8_feb05143307_Results.txt\" 1000000 500000 100 100000 22 1 1 0 -1 1 1
```

When I tried running the command directly in the command line, I got the following error:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 14 out of bounds for length 14
	at Objects.Arguments.<init>(Arguments.java:326)
	at bglims.BGLiMS.main(BGLiMS.java:78)
```

The last example, in which data from the MendelianRandomization package is used, is working, but I get the following warnings:

```
Warning messages:
1: In JAMMR(ldlc, ldlcse, chdlodds, chdloddsse, N1 = 17723, eafs = lipid_eaf,  :
  JAM-MR assigned non-zero probability to the null model.
2: In JAMMR(ldlc, ldlcse, chdlodds, chdloddsse, N1 = 17723, eafs = lipid_eaf,  :
  JAM-MR assigned non-zero probability to the null model.
3: In JAMMR(ldlc, ldlcse, chdlodds, chdloddsse, N1 = 17723, eafs = lipid_eaf,  :
  JAM-MR assigned non-zero probability to the null model.
4: In JAMMR(ldlc, ldlcse, chdlodds, chdloddsse, N1 = 17723, eafs = lipid_eaf,  :
  JAM-MR assigned non-zero probability to the null model.
5: In JAMMR(ldlc, ldlcse, chdlodds, chdloddsse, N1 = 17723, eafs = lipid_eaf,  :
  JAM-MR assigned non-zero probability to the null model.
6: In JAMMR(ldlc, ldlcse, chdlodds, chdloddsse, N1 = 17723, eafs = lipid_eaf,  :
  JAM-MR assigned non-zero probability to the null model.
```

Cheers,
Gabriel

**Comment by pjnewcombe** [comment]
Hi Gabriel,

Many thanks for letting me know - and your detailed debugging! I think we have an idea what went wrong (and it related to the other effect estimation function too). Will be in touch very soon.

Best,
Paul

**Comment by pjnewcombe** [comment]
Hi Gabriel

Again - apologies for closing this issue! 

First, I have just uploaded a new version to Github which fixed a bug.

Regarding the first error message - perhaps the issue is now fixed in the update. Otherwise, we were unable to reproduce this running the code below. Could you please email me an R script which causes the error? paul.newcombe@mrc-bsu.cam.ac.uk

Second - the warning message is by design - it flags when some null models have been visited (which will not be included in the causal effect estimation). We are currently working on making this warning much clearer and will let you know.

# ## Using an artificial dataset.
set.seed(21)
P <- 50
bx.sim <- rnorm(P, 0.15, 0.05)
sx.sim <- abs(rnorm(P, 0.02, 0.008))
which.pl <- rbinom(P, 1, 0.3)   ## Which SNPs are pleiotropic.
by.sim <- bx.sim * 0.5 + rnorm(P, 0, 0.05)   ## True causal effect is 0.5.
by.sim[which.pl == 1] <- by.sim[which.pl == 1] + rep(0.25, sum(which.pl))   ## Pleiotropic effects.
sy.sim <- abs(rnorm(P, 0.04, 0.01))

### Visualize the data.
#plot(bx.sim, by.sim, type = "p", pch = 19, xlim = c(0.00, 0.30), ylim = c(-0.10, 0.45), main = "Bx-By Plot")
#for (i in 1:50) lines(c(bx.sim[i], bx.sim[i]), c(by.sim[i] - 1.96 * sy.sim[i], by.sim[i] + 1.96 * sy.sim[i]))
#for (i in 1:50) lines(c(bx.sim[i] - 1.96 * sx.sim[i], bx.sim[i] + 1.96 * sx.sim[i]), c(by.sim[i], by.sim[i]))
#abline(a = 0, b = median(by.sim / bx.sim), col = "brown", lty = 2)

### Run JAM-MR with a single value of w and independent data.
library(R2BGLiMS)
jammr.results1 <- JAMMR(bx.sim, sx.sim, by.sim, sy.sim, N1 = 10000, eafs = rep(0.3, 50),
                        iter = 1e6, w = 10000, jam.seed = 22)

**Comment by igbucur** [comment]
Hi Paul,

Thanks for the quick and detailed reply. The Java input error is gone with the latest update, so I am closing this issue. There is still the problem with the output of JAM-MR, which I have reported in #13 .
