### ISSUE TITLE
Error: the leading minor of order 139 is not positive definite

### ISSUE THREAD

**Issue by edm1** [pjnewcombe/R2BGLiMS#7]
Hi,

I'm trying to use JAM for the first time and getting the following error:

```
Setting tau to max(n,P^2)
Number of million iterations specified. Overriding n.iter.
1e+06 iterations will be run...
Writing data into an input file for BGLiMS...
Error in chol.default(xTx[[b]]) : 
  the leading minor of order 139 is not positive definite
Calls: JAM -> R2BGLiMS -> .WriteData -> chol -> chol.default
Execution halted
```

I'm not sure whats causing the problem. Is this something you have seen before?

Thanks,
Ed

**Comment by pjnewcombe** [comment]
Hello,

First of all, thank you for the interest in JAM!

This sort of error normally happens if the reference data is too sparse, i.e. the number of people is "too small" relative to the number of SNPs. This can lead to a reference matrix which is not full rank, and hence not positive definite. 

If this is the issue you could try:
- LD pruning, so that the SNPs are less correlated (e.g. max correlation <0.95 or <0.9). Highly correlated SNPs are more likely to lead to non-full rank matrices.
- Splitting the SNPs up into 2 or more blocks where independence can be roughly assumed.

You can check whether your reference data is positive definite using the "JAM_RankCheck" function inside R2BGLiMS.

Let me know how it goes.

Cheers,
Paul

**Comment by edm1** [comment]
I was using 770 SNPs x ~150k samples as the reference data but there was clearly a lot of correlation in there. After removing SNPs in high LD I was left with 151 variants and JAM ran as expected.

Thanks for the help.

**Comment by pjnewcombe** [comment]
Brilliant! Thanks for persevering, and letting me know.

That's the largest reference data JAM has ever been used with, so you are in new territory :-)

Cheers,
Paul
